version: 1.0

telegram:
  state: 1
  interval: 1800
currencies:
  - name: "Ethereum"
    key: "ETH-EUR"
    min: 1000
    max: 2800
  - name: "Solana"
    key: "SOL-EUR"
    min: 7
    max: 145
  - name: "Cardano"
    key: "ADA-EUR"
    min: 0.19
    max: 1.5
  - name: "Stellar"
    key: "XLM-EUR"
    min: 0.03
    max: 0.31
  - name: "Polkadot"
    key: "DOT-EUR"
    min: 3.9
    max: 36
  - name: "Uniswap"
    key: "UNI-EUR"
    min: 4.2
    max: 18.7